default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: hotel_reservation_api_development

test:
  <<: *default
  database: hotel_reservation_api_test

production:
  <<: *default
  database: hotel_reservation_api_production
  username: hotel_reservation_api
  password: <%= ENV['HOTEL_RESERVATION_API_DATABASE_PASSWORD'] %>
